# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 627981ae66cf0a5bf0f6dd75fde4b48b2204e789404c14413365d3085c90d43fb8f4e8cd46f8081e17e2da69266f39a022bf92fcfb6d790caac4fdc43c153d0a

test:
  secret_key_base: 4659dd640c48d32be8abbeba987b347e2c830184a07209e870414b1842dafc041340030b85a8efe5429d3d1f8cf123c118a59ddb84b7d55339fb46d718093642

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
